export const ARTISTLIST_ALL = 'ARTISTLIST_ALL';
export const GET_ARTIST_SEARCH = 'GET_ARTIST_SEARCH';
export const GET_ARTIST_DETAIL = 'GET_ARTIST_DETAIL';
export const CLEAR_ARTIST_DETAIL = 'CLEAR_ARTIST_DETAIL';